import { Inter } from 'next/font/google'
import './globals.css'
import HomePage from './page'
import Navbar from '@/component/root_navbar/Navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      
      <body className={inter.className}>
        <h1 className='flex justify-center p-8 text-3xl text-red-700'> Navigating Between Pages</h1>
        <Navbar/>
        {children}
        
      </body>
      
    </html>
  )
}
